# Build SystemInfo Plugin

name: Build SystemInfo Plugin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: /home/runner/work/SystemInfo/SystemInfo/target/*-SNAPSHOT.jar
        if-no-files-found: error
